# Generated by Django 5.2 on 2025-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coupon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
