# Generated by Django 5.2 on 2025-04-07 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='products/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp'])]),
        ),
    ]
