# Generated by Django 5.2 on 2025-04-07 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('-created_at',), 'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp'])]),
        ),
    ]
