"""
This type stub file was generated by pyright.
"""

def require_show_toolbar(view): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], CoroutineType[Any, Any, Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """
    Async compatible decorator to restrict access to a view
    based on the Debug Toolbar's visibility settings.
    """
    ...

def render_with_toolbar_language(view): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Force any rendering within the view to use the toolbar's language."""
    ...

