"""
This type stub file was generated by pyright.
"""

from functools import cache
from django.dispatch import receiver
from django.test.signals import setting_changed

CONFIG_DEFAULTS = ...
@cache
def get_config(): # -> dict[str, Any]:
    ...

PANELS_DEFAULTS = ...
@cache
def get_panels(): # -> list[Any | str] | list[Any] | list[str]:
    ...

@receiver(setting_changed)
def update_toolbar_config(*, setting, **kwargs): # -> None:
    """
    Refresh configuration when overriding settings.
    """
    ...

