"""
This type stub file was generated by pyright.
"""

from debug_toolbar._compat import login_not_required
from debug_toolbar.decorators import render_with_toolbar_language, require_show_toolbar

@login_not_required
@require_show_toolbar
@render_with_toolbar_language
def render_panel(request): # -> JsonResponse:
    """Render the contents of a panel"""
    ...

